// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wiqcawxfidobsbfgpboa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpcWNhd3hmaWRvYnNiZmdwYm9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMDgwMTcsImV4cCI6MjA2NTg4NDAxN30.Di_s4Cx8yQrvSe7oY0oKIgTETRdloD0bwVs7ivNvX4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);